name: Update CSVs daily

on:
  schedule:
    - cron: "0 9 * * *"   # cada día a las 09:00 UTC
  workflow_dispatch:      # también se puede lanzar manualmente

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Run update script
        run: python update_csv.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add taa-dashboard/data/*.csv
          git commit -m "Auto-update CSVs ($(date -u +'%Y-%m-%d %H:%M:%S'))" || echo "No changes to commit"
          git push
